### ISSUE TITLE
Installation Travis CI

### ISSUE THREAD

**Issue by drosofff** [IFB-ElixirFr/ProMetIS#1]
Salut @ethevenot

Je viens de recevoir une alerte me demandant de t'autoriser à installer le hook avec travis-ci.

Je me demande bien pourquoi on me demande cela à moi, et je vais volontiers de la donner si tu me confirmes que c'est bien ce que tu veux.

Cela dit, je te signale que Travis-CI est devenu payant et qu'à ARTbio nous sommes en train de migrer sur le CI intégré de GitHub (les "Actions"). Je râle parce qu'il faut réapprendre une nouvelle API, mais bon, ça va, ce n'est pas trop trop raide (juste du temps pas prévu). Même chose pour le galaxyproject.

Cheers

**Comment by ethevenot** [comment]
Bonjour Christophe,
Désolé de t'importuner avec cette demande. Je suivrai avec plaisir ta suggestion d'utiliser le CI de GitHub. Donc pas de demande de Travis de mon côté. Merci beaucoup. Etienne.

**Comment by lecorguille** [comment]
Oui, je suis aussi en train de migrer sur les Action de GitHub.
@ethevenot Je pense que tu pourras trouver facilement des repo R qui implementes ce CI
